name: publish @rumsan/user to npm
on:
  push:
    branches:
      - publish

jobs:
  publish-user-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/user

    steps:
      - name: checkout publish branch
        uses: actions/checkout@v3
        with:
          ref: publish

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.RSLIB_NPM_TOKEN }}
          package: ./package.json
          access: restricted
          
