name: publish @rumsan/user to npm
on:
  push:
    branches:
      - publish

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout publish branch
        uses: actions/checkout@v3
        with:
          ref: publish

      - name: publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.RSLIB_NPM_TOKEN }}
          package: ./packages/user/package.json
          access: restricted
          
