name: publish @rumsan/user to npm
on:
  push:
    branches:
      - main

jobs:
  publish-user-npm:
    runs-on: ubuntu-latest

    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: user to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.RSLIB_NPM_TOKEN }}
          package: ./packages/user/package.json
          access: public

      - name: notify to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.RSLIB_NPM_TOKEN }}
          package: ./packages/notify/package.json
          access: public

      - name: core to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.RSLIB_NPM_TOKEN }}
          package: ./packages/core/package.json
          access: public

      - name: sms to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.RSLIB_NPM_TOKEN }}
          package: ./packages/sms/package.json
          access: public

      - name: pin to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.RSLIB_NPM_TOKEN }}
          package: ./packages/pin/package.json
          access: public
