name: publish @rumsan/user to npm
on:
  push:
    branches:
      - publish

jobs:
  publish-user-npm:
    runs-on: ubuntu-latest

    steps:
      - name: checkout publish branch
        uses: actions/checkout@v3
        with:
          ref: publish

      - uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: publish to npm
        run: |
          npm-publish --token=${{ secrets.RSLIB_NPM_TOKEN }} --access="restricted" ./packages/user/package.json
